// const createIssue = require('./create-issue.js');
// const createProject = require('./create-project.js');
// const getIssueByID = require('./get-issue-by-id.js');
// const deleteIssueByID = require('./delete-issue-by-id.js');
// const getIssues = require('./get-issues.js');
// const getTransitions = require('./get-transitions.js');
// const getUsers = require('./get-users.js');
// const updateStatus = require('./update-status.js');
// const getProjects = require('./get-projects.js')


// const createProjectIssueAndUpdate = async () => {

//   const projectName = process.env.PROJECT_NAME
//   const projectKey = await createProject(projectName);
//   console.log(`Created project with key: ${projectKey}`);

//   const issueType = 'Task';
//   const summary = 'Subscribe to Horeas YouTube Channel!';
//   const description = 'Do so now!!'

//   const issueKey = await createIssue(projectKey, issueType, summary, description);
//   console.log(`Created issue with key: ${issueKey}`);

//   // Notes about statusID: statusID corresponds to " 11 == "To Do", 21=="In Progress", 31=="In Review", 41=="Done"
//   // for more info on statusID use the `get-transtions.js` file to see all available transitions
//   // since we are hard coding `21` below this means we will update the issue to In Progress
//   const statusID = '21'

//   // Add issueKey you want to update. This will be the key which we autogenerated from the issue above.
//   const update = await updateStatus(issueKey, statusID);
//   console.log(update)
// }

// //This will output the most recent projects
// const getRecentProjects = async () => {
//   const recentProjects = await getProjects();
//   console.log(recentProjects)
// }

// //This will list all issues for a project
// const getIssuesFunc = async () => {
//   const issues = await getIssues();
//   console.log(issues)
// }

// // This will list all transitions for a project, make sure to change the issueKey to correspond
// // with your project!
// const getTransitionsFunc = async (issueKey) => {
//   const transitions = await getTransitions(issueKey);
//   console.log(transitions)
// }

// const getIssueByIDFunc = async (issueKey) => {
//   const issue = await getIssueByID(issueKey);
//   console.log(issue)
// }

// const deleteIssueByIDFunc = async (issueKey) => {
//   const issue = await deleteIssueByID(issueKey);
//   console.log(issue)
// }

// const updateStatusFunc = async (issueKey, statusID) => {
//   const status = await updateStatus(issueKey, statusID);
//   console.log(status)
// }

// // This will list all users
// const getUsersFunc = async () => {
//   const users = await getUsers();
//   console.log(users)
// }

